[package]
name = "ASCII_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"  # Работа с изображениями
clap = {version = "4.5", features = ["derive"]} # CLI
ansi_term = "0.12" # Цветной вывод
anyhow = "1.0" # Удобные ошибки